package org.example.project.adb

/**
 * adb cheat sheet
 *
 * @author YangJianyu
 * @date 2024/8/30
 */
const val ANDROID_HOME_PATH_HOLDER = "{ANDROID_HOME_PATH_HOLDER}"
const val SCRCPY_PATH_HOLDER = "{SCRCPY_PATH_HOLDER}"

const val PACKAGE_NAME_HOLDER = "{PACKAGE_NAME_HOLDER}"
const val FILE_PATH_HOLDER = "{FILE_NAME_HOLDER}"
const val DIR_PATH_HOLDER = "{DIR_NAME_HOLDER}"
const val ADB_PATH_HOLDER = "{ADB_PATH_HOLDER}"
const val PID_HOLDER = "{PID_HOLDER}"
const val ACTION_HOLDER = "{ACTION_HOLDER}"
const val DISPLAY_ID_HOLDER = "{DISPLAY_ID_HOLDER}"

const val PUSH_SOURCE_PATH = "{PUSH_SOURCE_PATH}"
const val PUSH_TARGET_PATH = "{PUSH_TARGET_PATH}"

const val PULL_SOURCE_PATH = "{PULL_SOURCE_PATH}"
const val PULL_TARGET_PATH = "{PULL_TARGET_PATH}"

const val RENAME_OLD_FILE_PATH = "{RENAME_OLD_FILE_PATH}"
const val RENAME_NEW_FILE_PATH = "{RENAME_NEW_FILE_PATH}"

const val REMOVE_TARGET_PATH = "{REMOVE_TARGET_PATH}"

const val MCC_HOLDER = "{MCC_HOLDER}"
const val SPACE_HOLDER = "{SPACE_HOLDER}"


// root
const val ADB_ROOT = "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}root"
const val ADB_REMOUNT = "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}remount"

// device control
// ADB commands
const val ADB_REBOOT = "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}reboot"

// Device info
const val ADB_DEVICE_LIST = "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}devices"
const val ADB_DEVICE_BRAND =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}getprop${SPACE_HOLDER}ro.product.brand"
const val ADB_DEVICE_NAME =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}getprop${SPACE_HOLDER}ro.product.model"
const val ADB_ANDROID_VERSION =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}getprop${SPACE_HOLDER}ro.build.version.sdk"
const val ADB_BUILD_VERSION =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}getprop${SPACE_HOLDER}ro.build.display.id"

// App control
const val ADB_KILL_APP =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}force-stop${SPACE_HOLDER}${PACKAGE_NAME_HOLDER}"
const val ADB_START_APP =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}monkey${SPACE_HOLDER}-p${SPACE_HOLDER}${PACKAGE_NAME_HOLDER}${SPACE_HOLDER}-c${SPACE_HOLDER}android.intent.category.LAUNCHER${SPACE_HOLDER}1"

// App install/uninstall
const val ADB_INSTALL =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}install${SPACE_HOLDER}${FILE_PATH_HOLDER}" // + apk path
const val ADB_UNINSTALL =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}uninstall${SPACE_HOLDER}${PACKAGE_NAME_HOLDER}" // + package name

// Package manager commands
const val ADB_APP_VERSION =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}dumpsys${SPACE_HOLDER}package${SPACE_HOLDER}${PACKAGE_NAME_HOLDER}${SPACE_HOLDER}|${SPACE_HOLDER}grep${SPACE_HOLDER}versionName"
const val ADB_PRINT_PATH =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}pm${SPACE_HOLDER}list${SPACE_HOLDER}packages${SPACE_HOLDER}-f${SPACE_HOLDER}|${SPACE_HOLDER}grep${SPACE_HOLDER}${PACKAGE_NAME_HOLDER}" // + package name
const val ADB_CLEAR_DATA =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}pm${SPACE_HOLDER}clear${SPACE_HOLDER}${PACKAGE_NAME_HOLDER}" // + package name
const val ADB_THIRD_PARTY_APP =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}pm${SPACE_HOLDER}list${SPACE_HOLDER}packages${SPACE_HOLDER}-3"
const val ADB_FIND_PID_BY_PACKAGE_NAME =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}pidof${SPACE_HOLDER}${PACKAGE_NAME_HOLDER}"

const val ADB_PUSH =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}push${SPACE_HOLDER}${PUSH_SOURCE_PATH}${SPACE_HOLDER}${PUSH_TARGET_PATH}"
const val ADB_PULL =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}pull${SPACE_HOLDER}'${PULL_SOURCE_PATH}'${SPACE_HOLDER}'${PULL_TARGET_PATH}'"
const val ADB_RENAME =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}mv${SPACE_HOLDER}'${RENAME_OLD_FILE_PATH}'${SPACE_HOLDER}'${RENAME_NEW_FILE_PATH}'"
const val ADB_REMOVE =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}rm${SPACE_HOLDER}${REMOVE_TARGET_PATH}"

// ADB shell dumpsys commands
const val ADB_DUMP_MEM_INFO =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}dumpsys${SPACE_HOLDER}meminfo${SPACE_HOLDER}${PACKAGE_NAME_HOLDER}"
const val ADB_DUMP_SHOW_TOP_ACTIVITY =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}dumpsys${SPACE_HOLDER}activity${SPACE_HOLDER}top${SPACE_HOLDER}|${SPACE_HOLDER}grep${SPACE_HOLDER}ACTIVITY"

// Screen shot commands
const val ADB_FIND_ACTIVE_DISPLAY =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}dumpsys${SPACE_HOLDER}SurfaceFlinger${SPACE_HOLDER}|${SPACE_HOLDER}grep${SPACE_HOLDER}\\(active\\)"
const val ADB_SCREEN_SHOT =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}screencap${SPACE_HOLDER}/sdcard/Pictures/Screenshots/screen_shot.png${SPACE_HOLDER}-d${SPACE_HOLDER}${DISPLAY_ID_HOLDER}"
const val ADB_SCREEN_START_RECORD =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}screenrecord${SPACE_HOLDER}/sdcard/Pictures/Screenshots/screen_record.mp4${SPACE_HOLDER}--d${SPACE_HOLDER}${DISPLAY_ID_HOLDER}"
const val ADB_SCREEN_FIND_RECORD_PID =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}pidof${SPACE_HOLDER}screenrecord"
const val ADB_SCREEN_STOP_RECORD =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}kill${SPACE_HOLDER}-2${SPACE_HOLDER}${PID_HOLDER}"

// Save screenshot and screen recording commands
const val ADB_SAVE_SCREEN_SHOT =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}pull${SPACE_HOLDER}/sdcard/Pictures/Screenshots/screen_shot.png${SPACE_HOLDER}${DIR_PATH_HOLDER}"
const val ADB_SAVE_SCREEN_RECORD =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}pull${SPACE_HOLDER}/sdcard/Pictures/Screenshots/screen_record.mp4${SPACE_HOLDER}${DIR_PATH_HOLDER}"

// Open language change setting command
const val ADB_OPEN_SETTING =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}start${SPACE_HOLDER}-a${SPACE_HOLDER}android.settings.SETTINGS"
const val ADB_OPEN_LANGUAGE_SETTING =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}start${SPACE_HOLDER}-a${SPACE_HOLDER}android.settings.LOCALE_SETTINGS"
const val ADB_OPEN_DATE_SETTING =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}start${SPACE_HOLDER}-a${SPACE_HOLDER}android.settings.DATE_SETTINGS"
const val ADB_OPEN_DATA_ROAMING_SETTING =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}start${SPACE_HOLDER}-a${SPACE_HOLDER}android.settings.DATA_ROAMING_SETTINGS"
const val ADB_OPEN_HONOR_SIM_SETTING =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}start${SPACE_HOLDER}-n${SPACE_HOLDER}com.hihonor.dsdscardmanager/.HWCardManagerActivity"
const val ADB_OPEN_WIFI_SETTING =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}start${SPACE_HOLDER}-a${SPACE_HOLDER}android.settings.WIFI_SETTINGS"
const val ADB_OPEN_ACCESSIBILITY_SETTING =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}start${SPACE_HOLDER}-a${SPACE_HOLDER}android.settings.ACCESSIBILITY_SETTINGS"
const val ADB_OPEN_APP_DETAIL_SETTING =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}start${SPACE_HOLDER}-a${SPACE_HOLDER}android.settings.APPLICATION_DETAILS_SETTINGS${SPACE_HOLDER}-d${SPACE_HOLDER}package:${PACKAGE_NAME_HOLDER}"


const val ADB_PATH_LIST_FILE =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}ls${SPACE_HOLDER}'${ADB_PATH_HOLDER}'"
const val ADB_PATH_CHECK_IS_DIRECTORY =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}test${SPACE_HOLDER}-d${SPACE_HOLDER}'${ADB_PATH_HOLDER}'${SPACE_HOLDER}&&${SPACE_HOLDER}echo${SPACE_HOLDER}\"true\"${SPACE_HOLDER}||${SPACE_HOLDER}echo${SPACE_HOLDER}\"false\""
const val ADB_PATH_CHECK_IS_FILE =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}test${SPACE_HOLDER}-f${SPACE_HOLDER}'${ADB_PATH_HOLDER}'${SPACE_HOLDER}&&${SPACE_HOLDER}echo${SPACE_HOLDER}\"true\"${SPACE_HOLDER}||${SPACE_HOLDER}echo${SPACE_HOLDER}\"false\""


// Honor MCC level commands
const val ADB_HONOR_GET_MCC_ENABLE_OVERSEA =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}settings${SPACE_HOLDER}get${SPACE_HOLDER}global${SPACE_HOLDER}redtea_enable_succ_lev" // 开启境外套餐
const val ADB_HONOR_PUT_MCC_ENABLE_OVERSEA =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}settings${SPACE_HOLDER}put${SPACE_HOLDER}global${SPACE_HOLDER}redtea_enable_succ_lev${SPACE_HOLDER}1" // 开启境外套餐
const val ADB_HONOR_DELETE_MCC_ENABLE_OVERSEA =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}settings${SPACE_HOLDER}delete${SPACE_HOLDER}system${SPACE_HOLDER}redtea_enable_succ_lev" // 关闭境外套餐

const val ADB_HONOR_GET_MCC_LEVEL =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}settings${SPACE_HOLDER}get${SPACE_HOLDER}system${SPACE_HOLDER}redtea_mcc_lev" // 启用 mcc 测试
const val ADB_HONOR_PUT_MCC_LEVEL =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}settings${SPACE_HOLDER}put${SPACE_HOLDER}system${SPACE_HOLDER}redtea_mcc_lev${SPACE_HOLDER}2" // 启用 mcc 测试
const val ADB_HONOR_DELETE_MCC_LEVEL =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}settings${SPACE_HOLDER}delete${SPACE_HOLDER}system${SPACE_HOLDER}redtea_mcc_lev" // 清除 mcc 测试参数

// Honor MCC commands
const val ADB_HONOR_GET_MCC =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}settings${SPACE_HOLDER}get${SPACE_HOLDER}global${SPACE_HOLDER}redtea_mcc" // + mcc 设置 mcc
const val ADB_HONOR_PUT_MCC =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}settings${SPACE_HOLDER}put${SPACE_HOLDER}global${SPACE_HOLDER}redtea_mcc${SPACE_HOLDER}${MCC_HOLDER}00,${MCC_HOLDER}01" // + mcc 设置 mcc

const val ADB_HONOR_MCC_BROAD_CAST_SEND =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}broadcast${SPACE_HOLDER}-a${SPACE_HOLDER}com.hihonor.general.vsim.action.VSIM_REG_PLMN_CHANGED${SPACE_HOLDER}--es${SPACE_HOLDER}mcc${SPACE_HOLDER}${MCC_HOLDER}" // + mcc 发送 mcc 广播


// Oppo MCC commands
const val ADB_OPPO_GET_MCC_1 =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}getprop${SPACE_HOLDER}android.telephony.mcc_change"
const val ADB_OPPO_PUT_MCC_1 =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}setprop${SPACE_HOLDER}android.telephony.mcc_change${SPACE_HOLDER}${MCC_HOLDER}"

const val ADB_OPPO_GET_MCC_2 =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}getprop${SPACE_HOLDER}android.telephony.mcc_change2"
const val ADB_OPPO_PUT_MCC_2 =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}setprop${SPACE_HOLDER}android.telephony.mcc_change2${SPACE_HOLDER}${MCC_HOLDER}"

const val ADB_OPPO_MCC_BROAD_CAST_SEND =
    "${ANDROID_HOME_PATH_HOLDER}adb${SPACE_HOLDER}shell${SPACE_HOLDER}am${SPACE_HOLDER}broadcast${SPACE_HOLDER}-a${SPACE_HOLDER}android.telephony.action.mcc_change${SPACE_HOLDER}--es${SPACE_HOLDER}mcc${SPACE_HOLDER}${MCC_HOLDER}${SPACE_HOLDER}-n${SPACE_HOLDER}com.redteamobile.roaming/.receiver.MccChangeReceiver"

const val SCREEN_COPY =
    "ADB=${ANDROID_HOME_PATH_HOLDER}/platform-tools/adb${SPACE_HOLDER}${SCRCPY_PATH_HOLDER}/scrcpy"